# Generated by Django 5.2.7 on 2025-12-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
